### ISSUE TITLE
Crash on entering campfires

### ISSUE THREAD

**Issue by STSsadoni** [alexdriedger/ChallengeTheSpire#11]
Looks like an infinite loop.

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.StackOverflowError
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.StackOverflowError
	at com.evacipated.cardcrawl.mod.hubris.patches.TeleporterPatch$IsConnectedTo.getNodeDistance(TeleporterPatch.java:88)
	at com.evacipated.cardcrawl.mod.hubris.patches.TeleporterPatch$IsConnectedTo.getNodeDistance(TeleporterPatch.java:93)
	at com.evacipated.cardcrawl.mod.hubris.patches.TeleporterPatch$IsConnectedTo.getNodeDistance(TeleporterPatch.java:93)
	at com.evacipated.cardcrawl.mod.hubris.patches.TeleporterPatch$IsConnectedTo.getNodeDistance(TeleporterPatch.java:93)
	at com.evacipated.cardcrawl.mod.hubris.patches.TeleporterPatch$IsConnectedTo.getNodeDistance(TeleporterPatch.java:93)
	at com.evacipated.cardcrawl.mod.hubris.patches.TeleporterPatch$IsConnectedTo.getNodeDistance(TeleporterPatch.java:93)
	at com.evacipated.cardcrawl.mod.hubris.patches.TeleporterPatch$IsConnectedTo.getNodeDistance(TeleporterPatch.java:93)
	at com.evacipated.cardcrawl.mod.hubris.patches.TeleporterPatch$IsConnectedTo.getNodeDistance(TeleporterPatch.java:93)

**Comment by alexdriedger** [comment]
Thanks for submitting the bug. It is now fixed (version 1.2.3+)
